ruby "2.4.1"
source "https://rubygems.org"

gem "sinatra", :require => "sinatra/base"
gem "thin"
gem "kramdown"
gem "redis"
gem "redis-asm"
gem "tsv"
gem "bk", :path => "../lib/bktree"

group :development do
  gem "rack-test"
  gem "rubocop"
  gem "bacon"
  gem "rspec"
end

group :debug do
  gem "byebug"
  gem "pry-byebug"
end
