source "https://rubygems.org"
gem "sinatra", :require => "sinatra/base"
gem "thin"
gem "kramdown"
gem "redis"
gem "redis-asm"
gem "tsv"

group :development do
  gem "rack-test"
  gem "rubocop"
  gem "bacon"
  gem "pry"
end
